Building Feel++
===============

:toc:
:toc-placement: macro
:toclevels: 3

toc::[]
Once the steps to install on Linux
In this section, we will explain how to download and build Feel++ from source.

== For the impatient

First retrieve the source
[source,bash]
----
$ git clone https://github.com/feelpp/feelpp.git
----

Create a build directory
[source,bash]
----
$ mkdir build
$ cd build
----

Configure Feel++
[source,bash]
----
$ CXX=clang++ ../feelpp/configure -r
----

Compile the Feel++ library 
[source,bash]
----
$ make feelpp
----

> **Tip:** you can speed up the make process by passing the option `-j<N>` where `N` is the number of concurrent `make` sub-processes. It compiles `N` files at a time and respect dependencies. For example `-j4` compiles 4 C++ files at a time. 

> **Warning:** Be aware that Feel{plus}{plus} consumes memory. The Feel{plus}{plus} library compile with 2Go of RAM. But to be more comfortable, 4Go or more would be best. The more, the better.

Compile your first Feel++ applications
[source,bash]
----
$ make quickstart
----

Execute your first Feel++ application in sequential
[source,sh]
----
$ cd quickstart
$ ./feelpp_qs_laplacian_2d --config-file qs_laplacian_2d.cfg
----


Execute your first Feel++ application using 4 mpi processes
[source,sh]
----
$ mpirun -np 4 feelpp_qs_laplacian_2d --config-file qs_laplacian_2d.cfg
----


== Downloading Feel++ sources

[[tarballs]]
=== Tarballs

Feel++ is distributed as tarballs following each major release. The tarballs are available on the  link:https://github.com/feelpp/feelpp/releases[Feel++ Releases] web page.

Download the latest tarball, then uncompress it with:

[source,sh]
----
$ tar -xzf feelpp-X.YY.0.tar.gz
$ cd feelpp-X.YY.0
----

You can now move to the section <<cmake>>.

[[git]]
=== Getting the source via Git

Alternatively, you can download the sources of Feel++ directly from link:https://github.com/feelpp/feelpp[the Git repository].

[source,sh]
----
$ git clone  https://github.com/feelpp/feelpp.git
----

You should read something like
[source,sh]
----
Cloning into 'feelpp'...
remote: Counting objects: 129304, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 129304 (delta 6), reused 0 (delta 0), pack-reused 129283
Receiving objects: 100% (129304/129304), 150.52 MiB | 1.69 MiB/s, done.
Resolving deltas: 100% (94184/94184), done.
Checking out files: 100% (7237/7237), done.
----

[source,sh]
----
$ cd feelpp
----

The first level directory tree is as follows
[source,sh]
----
$ tree -L 1 -d | column
.			├── databases		├── research
├── applications	├── doc			├── testsuite
├── benchmarks		├── feel		└── tools
├── cmake		├── ports		14 directories
├── contrib		├── projects
├── data		├── quickstart
----

== Compiling Feel++ 




=== Detailed build instructions

Feel{plus}{plus} uses http://www.cmake.org[`CMake`] as its build system. Check that CMake is using `clang-3.5` (or a higher version) (or `g++`, but it has a huge memory footprint) as C{plus}{plus} compiler. You can set the compiler with following option :
```
-DCMAKE_CXX_COMPILER=<path>/clang++-3.5
``` 
where the `path` depends on your OS. By default, it should be `/usr/bin` or `/opt/local/bin`, but you can also change it with the command `ccmake` and press `t` for advanced options). +



In order to compile and install Feel{plus}{plus} on Linux systems (other than Mac OS X, if you have Mac OS X, please go to link:mac.adoc[Mac]), you have to install several dependencies before. Those libraries and programs are necessary for the compilation and installation of the Feel++ libraries.


=== Configuration step 

> **Warning** It is not allowed to build the library in the top source directory.

It is recommended  to have a directory (e.g. `FEEL`) in which you have
both the sources and build directories.

[source,sh]
----
ls FEEL
feelpp/ # Sources
feel.opt/ # Build directory
----

`feelpp` is the top directory where the source have been downloaded, using git or tarballs.

[[cmake]]
==== Using cmake directly

`CMake` is used as it:

[source,sh]
----
cd FEEL/feel.opt
cmake ../feelpp -DCMAKE_CXX_COMPILER=/usr/bin/clang++-3.6 -DCMAKE_C_COMPILER=/usr/bin/clang-3.6 -DCMAKE_BUILD_TYPE=RelWithDebInfo
----

> **Info**: CMake supports different build type that you can set with `-DCMAKE_BUILD_TYPE` (case insensitive) :
> 
 * None
 * Debug : typically `-g`
 * Release : typically `-O3`
 * MinSizeRel : typically `-Os`
 * RelWithDebInfo :  typically `-g -O2`

==== Using the configure script

Alternatively you can use the `configure` script which calls `cmake`. `configure --help` will provide the following help.
[source,sh]
.Listing Configure help
----
Options: 
 -b, --build                         build type: Debug, Release, RelWithDebInfo                                                   
 -d, --debug                         debug mode                             
-rd, --relwithdebinfo                relwithdebinfo mode 
 -r, --release                       release mode  
     --std=c++xx                     c++ standard: c++14, c++1z (default: c++14)                                                   
     --stdlib=libxx                  c++ standard library: stdc++(GCC), c++(CLANG) (default: stdc++)                                  
     --max-order=x                   maximum polynomial order to instantiate(default: 3)                                          
     --cxxflags                      override cxxflags    
     --cmakeflags                    add extra cmake flags 
     --prefix=PATH                   define install path  
 -v, --verbose                       enable verbose output 
 -h, --help                          help page       
     --<package>-dir=PACKAGE_PATH    define <package> install directory   
     --disable-<package>             disable <package>     
     --generator=GENERATOR           cmake generator       
----

We display below a set of possible configurations:
[source,sh]
.Feel++ configure options
----
cd feelpp.opt/
# compile using Release build type, default c++ compiler and libstdc++
../feelpp/configure -r
# compile using Release build type, clang++ compiler and libstdc++
CXX=clang++ ../feelpp/configure -r
# compile using Debug build type, clang++ compiler and libc++ 
CXX=clang++ ../feelpp/configure -d -stdlib=c++
----

==== Advanced configuration setting

===== Per-system specific configuration

If you need to set specific CMake variables to fit an exotic system (e.g. supercomputer), you can create a machine file fitting this system. + 
To do so, simply create a file named `feelpp.machines.<name>.cmake` in the `cmake/machines` directory, where `<name>` is the machine name returned by the execution of `uname -n`. The file will automatically be recognized and loaded, when you will be compiling Feel++ on this system.  

==== Compilation step

Once CMake has done its work, you are now able to compile the library with:

[source,bash]
----
make
----

You can speed up the compilation process, if you have a multicore processor. To do so, you can specify the number of parallel jobs `make` will be allowed to spawn by using the `-j` flag:

[source,bash]
----
# build Feel++ library
# make -j <nbjobs>
make -j4 feelpp
----

> **Note** From now on, all commands should be typed in
  build directory (e.g `feel.opt`) or its subdirectories.

==== Running the Feel++ Testsuite

If you encounter issues with Feel++, you can run the testsuite and send the resulting report. Feel{plus}{plus} has more than 300 tests running daily on our servers. Most of the tests are run both in sequential and in parallel.

In order to run the testsuite, follow the steps below

.Listing: Running the Feel++ testsuite
[source,bash]
----
cd testsuite
ctest -j4 -R .
----
It will run 4 tests at a time thanks to the option `-j4`.
