Prerequisites
=============

== Compilers

Feel{plus}{plus} uses C{plus}{plus}14 compilers such as GCC6 and Clang. Currently it is not mandatory to have a C++14 stantard library but it will be soon.

> **Warning:** There used to be a major compatibility issue between llvm/clang and GCC compilers since GCC5 released the ABI tag which makes it impossible to compile Feel{plus}{plus} using llvm/clang with GCC5 or GCC6 standard libraries for a time. Please see the following table to understand the working C{plus}{plus} compiler / C{plus}{plus} standard library combinations.

.Table C{plus}{plus} compilers and standard libraries combinations
|===
| Compiler  | Standard Library 

| clang (3.6, 3.7, 3.8) | libstdc{plus}{plus} 4.9 
| clang  |  libc{plus}{plus} (corresponding clang version)
| clang (3.8(requires patches), 3.9)  | libstdc{plus}{plus} 6
| GCC 6 | libstdc{plus}{plus} 6

|===

== Required tools and libraries

Other than C{plus}{plus}14 compilers, Feel{plus}{plus} requires only a few tools and libraries, namely CMake, Boost C++ libraries and an MPI implementation such as open-mpi or mpich. The table below provides information regarding the minimum and maximum version supported. A -- means it has not necessarily been tested with the latest version but we do not expect any issues. Note that for MPI, an implementation with MPI-IO support would be best.

.Table required tools to compile Feel++
|===
| Name | Minimum Version | Maximum Version | Notes

| CMake | 3.0 | -- | 
| MPI   | -- | -- | openmpi or mpich
| Boost | 1.55 | 1.63 | 

|===

== Optional tools and libraries

.Table optional external libraries

|===
| Library | Minimum Version | Maximum Version  | Notes

| PETSc | 3.2 | 3.7 | last is best
| SLEPc | 3.2 | 3.7 | last is best
| Gmsh  | 2.8.7 | 2.12 | last is best
| Superlu  ||| superlu and superlu_dist
| Suitesparse ||| umfpack (colamd,amd)
| OpenTURNS | 2.0 ||
|===

== Recommended tools

.Table Optional tools
|===
| Tool | Notes

| Paraview | for visualisation purposes
| Gmsh application | for meshing purposes
|===

Note that all these packages are available under Debian GNU/Linux and Ubuntu. Once you have installed those dependencies, you can go to link:#Compiling[Compiling].

== Suggested tools

.Table Optional tools
|===
| Tool | Notes

2+>| Computer Aided Design (CAD)  
| Freecad |
| Salome | 

2+>| Debugging and Profiling 
| Google perftools|
| Valgrind |

|===



