Prerequisites
=============

This is the list of all the libraries you must have installed on your computer, and the `*-dev` packages for some of them.


> **Warning** Feel{plus}{plus} use C{plus}{plus}14 compilers. There is a major compatibility issue between llvm/clang and GCC compilers since GCC5 released the ABI tag which makes it impossible to compile Feel{plus}{plus} using llvm/clang with GCC5 or GCC6 standard libraries. Please see the following table to understand the working C{plus}{plus} compiler / C{plus}{plus} standard library combinations.

.Table C{plus}{plus} compilers and standard libraries combinations
|===
| Compiler  | Standard Library 

| clang (3.6, 3.7, 3.8) | libstdc{plus}{plus} 4.9 
| clang  |  libc{plus}{plus} (corresponding clang version)
| clang (3.8, 3.9)  | libstdc{plus}{plus} 6
| GCC 6 | libstdc{plus}{plus} 6

|===



.Table required tools to compile Feel++
|===
| Name | Minimum Version | Maximum Version | Notes

| CMake | 3.0 | -- | 
| MPI   | -- | -- | openmpi or mpich
| Boost | 1.55 | 1.63 | 

|===


.Table optional external libraries

|===
| Library | Minimum Version | Maximum Version  | Notes

| PETSc | 3.2 | 3.7 | 
| Gmsh  | 2.8.7 | 2.12 | 
| Superlu  ||| superlu and superlu_dist
| Suitesparse ||| umfpack (colamd,amd)
| OpenTURNS |||
|===

.Table Optional tools
|===
| Tool | Notes

| Google perftools|
| Paraview | for visualisation purposes
| Gmsh application | for meshing purposes
|===

Note that all these packages are available under Debian GNU/Linux and Ubuntu. Once you have installed those dependencies, you can go to link:#Compiling[Compiling].

