Evaluating function 
==================
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

Once you  have created an element, you may want to give it a value, that can depends on a lot of parameters (mainly spaces, but others may apply).

To do so, Feel++ relies on expressions.
We may use various kind of expressions :

== Built-in 

Instead of defining an expression from a string, you can use

[source,c++]
----
{% include "code/05-myexporter.cpp" %}
----

The list of the Feel++ Keyword is link:../QuickReference/keywords.adoc[here].

This example represent the evaluation of the expression $$ sin(\pi x)$$ on a unit circle.

First at all, we define the unit circle and its link:07-SpaceElements.adoc[function space] :

----
 auto mesh = unitCircle<2>();
 auto Xh = Pch<2>( mesh );
----

Then the expression we would like to evaluate :
----
auto myExpr = sin(pi*Px());
----

Px() refers to the variable x of our space ( see link:../QuickReference/keywords.adoc#_Expressions[keywords] ).

To evaluate this, we will project it on our function space :
----
auto v = project( _space=Xh, _range=elements(mesh),
                  _expr=myExpr);
----

== Hard Coded 

One other method to define function is described here.

[source,c++]
----
{% include "code/myfunctor.cpp" %}
----
