= feelpp_mesh_partitioner
=========================
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

`feelpp_mesh_partitioner` is a simple applications which can generate a partitioned mesh and save it in a Feel++ specific  `json+hdf5`  file format. The generated mesh can then be loaded very efficiently in parallel.

== Options

`feelpp_mesh_partitioner` requires some options.

.Table of command-line `feelpp_mesh_partitioner` options
|===
| Name | Description | Default value
| `dim` | dimension of the mesh | 3
| `shape`| shape of the mesh elements | Simplex
| `part` | number of desired partitions | 
| `ifile` | name or path to the mesh | 
| `ofile` | output filename prefix (without extension) |
| `odir` | output directory | 
|===


== Examples

=== Generating a single mesh partitioning

We generate a mesh partitioned on 4 cores with the following command

[source,shell]
----
feelpp_mesh_partitioner --part 4  --ifile src/feelpp/data/gmsh/primitives/torus.geo --ofile torus
----



You should have in the current directory two files


[source,shell]
----
[ Starting Feel++ ] application mesh_partitioner version 0.102.00 date 2016-Dec-13
 . Results are stored in /home/feelpp
run partioner with shape Simplex_3_1_3
[loadMesh] Loading mesh in format geo+msh: "/home/feelpp/src/feelpp/data/gmsh/primitives/torus.geo"
[loadMesh] Use default geo desc: /home/feelpp/src/feelpp/data/gmsh/primitives/torus.geo 0.1 
      number of elements in memory : 84
      number of faces in memory : 60
      number of edges in memory : 0
      number of points  in memory : 36
      number of marked faces inlet with tag 1 : 14
      number of marked faces outlet with tag 2 : 14
      number of marked faces wall with tag 3 : 32
start mesh partitioning and save on disk : /home/feelpp/torus.json
[env] Time : 0.0306945s
[ Stopping Feel++ ] application mesh_partitioner execution time 0.0306945s
----