= feelpp_mesh_partitioner
=========================
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

`feelpp_mesh_partitioner` is a simple applications which can generate a partitioned mesh and save it in a Feel++ specific  `json+hdf5`  file format. The generated mesh can then be loaded very efficiently in parallel.

== Options

`feelpp_mesh_partitioner` requires some options.

.Table of command-line `feelpp_mesh_partitioner` options
|===
| Name | Description | Default value
| `dim` | dimension of the mesh | 3
| `shape`| shape of the mesh elements | Simplex
| `part` | number of desired partitions | 
| `ifile` | name or path to the mesh | 
| `ofile` | output filename prefix (without extension) |
| `odir` | output directory | 
|===


== Examples

=== Generating a single mesh partitioning

We generate a mesh partitioned on 4 cores with the following command

[source,shell]
----
feelpp_mesh_partitioner --part 4  --ifile src/feelpp/data/gmsh/primitives/torus.geo --ofile torus
----

You should have in the current directory 4 files

[source,shell]
----
ls torus*
torus.geo  torus.h5  torus.json  torus.msh
----

Now th file `torus.json` can be loaded in a Feel++ application distributed on 4 cores.

=== Generating multiple mesh partitioning

Often we are interested in a set of partitioned meshes in order to do a speed-up study. `feelpp_mesh_partitioner` is the right tool for that.
