= Solid Mechanics Models

== Properties

* Linear 
* SaintVenant Kirchhoff
* NeoHookean

When materials are closed to incompressibility formulation in displacement/pressure are available.

.Table of Models for `model` option
|===
| Model | Name 

| Linear Elasticity 
| `Elasticity`

| Hyper Elasticity 
| `Hyper-Elasticity`

|===

.Table of Models for `material_law` in hyper elasticity
|===
| Model | Name   | Volumic law

| SaintVenant Kirchhoff
| `SaintVenantKirchhoff`
| classic, simo1985

| NeoHookean
| `NeoHookean`
| classic, simo1985

|===

option: `mechanicalproperties.compressible.volumic_law`

== Boundary Conditions

Boundary conditions and volumic forces are set in the json files
[source,json]
.Example for boundary conditions
----
"BoundaryConditions":
{
    "field":
    {
        "<condition type>":
        {
            "marker":
            {
                "expr": "value"
            }
        }
    }
}
----
where all component of vectorial field can be access with `<field>_x` for the $$x$$ component where `<field>` is the name of the vectorial field. +
The condition types are explain in the following table.

.Boundary conditions
|===
| Name | Options  

| Dirichlet 
| faces, edges and component-wise

| Neumann 
| scalar, vectorial

| Pressure follower ,
| Nonlinear boundary condition set in deformed domain

| Robin 
| TODO

|===

.Volumic forces
|===
| Name | Options  

| Expression
| Vectorial

|===

== Post Process

[source,json]
----
"PostProcess":
{
    "Fields":["field1","field2",...],
    "Measures":
    {
        "<measure type>":
        {
            "label":
            {
                "<range type>":"value",
                "fields":["field1","field3"]
            }
        }
    }
}
----

The fields allowed to be exported in the `Fields` section are:

- displacement
- velocity
- acceleration
- stress or normal-stress
- pressure
- material-properties
- pid
- fsi
- Von-Mises
- Tresca
- principal-stresses
- all

In the `Measures` section, the measure type can be either the value on a set of points, `Points`, or the `Maximum` or `Minimum` over a set of range. +
In the case where one want to evaluate on a point, range type is `coords` and its value is the coordinate of the point (`"{0,0,0}"` for example). +
In the case where one want to evaluate over a range, range type is `markers` and its value is the name of the marker.

[options=headers]
|===
|Measure type | Range type | example
|Points | coords | "{0,0,0}"
|Maximum | markers | "marker1"
|Minimum | markers | "marker1"
|===

The fields on which one can do measures:

- volume_variation
- displacement
- velocity
- acceleration
- pressure
- principal-stress-0
- principal-stress-1
- principal-stress-2
- sigma_xx, sigma_xy, ...
