= Solid Mechanics Models
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

== Models

=== Incompressible Navier-Stokes model

Navier-Stokes model is used to modelise incompressible Newtonian fluid. It can be describe by these conservative laws :

* momentum conservation equation 

$$
\rho_{f} \left. \frac{\partial\mathbf{u}_f}{\partial t} \right|_\mathrm{x}
+ \rho_{f} \left( \boldsymbol{u}_{f} \cdot \nabla_{\mathrm{x}} \right) \boldsymbol{u}_{f}
- \nabla_{\mathrm{x}} \cdot \boldsymbol{\sigma}_{f} = \boldsymbol{f}^t_f , \quad \text{ in } \Omega^t_f \times \left[t_i,t_f \right]
$$

* mass conservation equation

$$
\nabla_{\mathrm{x}} \cdot \boldsymbol{u}_{f} = 0                     , \quad \text{ in } \Omega^t_f \times \left[t_i,t_f \right] 
$$

We add to them the material constitutive equation :

$$
\boldsymbol{\sigma}_{f} = -p_f \boldsymbol{I} + \mu_f (\nabla_\mathrm{x} \boldsymbol{u}_f + (\nabla_\mathrm{x} \boldsymbol{u}_f)^T)
$$


== Properties

* Linear 
* SaintVenant Kirchhoff
* NeoHookean

When materials are closed to incompressibility formulation in displacement/pressure are available.

.Table of Models for `model` option
|===
| Model | Name 

| Linear Elasticity 
| `Elasticity`

| Hyper Elasticity 
| `Hyper-Elasticity`

|===

.Table of Models for `material_law` in hyper elasticity
|===
| Model | Name   | Volumic law

| SaintVenant Kirchhoff
| `SaintVenantKirchhoff`
| classic, simo1985

| NeoHookean
| `NeoHookean`
| classic, simo1985

|===

option: `mechanicalproperties.compressible.volumic_law`

== Materials

[source,json]
.Materials section
----
"Materials":
{
    "marker":
    {
        "name":"solid",
        "E":"1.4e6",
        "nu":"0.4",
        "rho":"1e3"
    }
}
----

where `E` stands for the Young's modulus in $$Pa$$, `nu` the Poisson's ratio and `rho` the density in $$kg\cdot m^{-3}$$ .

== Boundary Conditions

Boundary conditions and volumic forces are set in the json files
[source,json]
.Example for boundary conditions
----
"BoundaryConditions":
{
    "field":
    {
        "<condition type>":
        {
            "marker":
            {
                "expr": "value"
            }
        }
    }
}
----
where all component of vectorial field can be access with `<field>_x` for the $$x$$ component where `<field>` is the name of the vectorial field. +
The condition types are explain in the two following tables.

.Boundary conditions
|===
| Name | Options | Type 

| Dirichlet 
| faces, edges and component-wise
| "Dirichlet"

| Neumann 
| scalar, vectorial
| "Neumann_scalar" or "Neumann_vectorial"

| Pressure follower ,
| Nonlinear boundary condition set in deformed domain
| TODO

| Robin 
| TODO
| TODO

|===

.Volumic forces
|===
| Name | Options | Type

| Expression
| Vectorial
| "VolumicForces"

|===

== Post Process

[source,json]
----
"PostProcess":
{
    "Fields":["field1","field2",...],
    "Measures":
    {
        "<measure type>":
        {
            "label":
            {
                "<range type>":"value",
                "fields":["field1","field3"]
            }
        }
    }
}
----

The fields allowed to be exported in the `Fields` section are:

- displacement
- velocity
- acceleration
- stress or normal-stress
- pressure
- material-properties
- pid
- fsi
- Von-Mises
- Tresca
- principal-stresses
- all

.Measure type and range type associated
|===
|Measure type | Range type | example

|Points | coords | "{0,0,0}"
|Maximum | markers | "marker1"
|Minimum | markers | "marker1"
|volume_variation* | - | "volume_variation":""
|===

*volume_variation does not take a set of point or of range, it is a volumic measure.

The fields on which one can do measures:

- volume_variation
- displacement
- velocity
- acceleration
- pressure
- principal-stress-0
- principal-stress-1
- principal-stress-2
- sigma_xx, sigma_xy, ...
