Feel++ Containers
=================
:toc:
:toc-placement: macro
:toclevels: 2

Feel++ leverages the power of Docker and provides a stack of container images. 

toc::[]



== First steps

To test Docker is installed properly, try
[source,bash]
----
$ docker run feelpp/feelpp-env  echo "Hello World!"
----

This may take a while depending on your internet connection but eventually you should see something like

[source,txt]
----
Unable to find image 'feelpp/feelpp-env:latest' locally
latest: Pulling from feelpp/feelpp-env
8e21f82d32cf: Pull complete 
[...]
0a8dee947f9b: Pull complete 
Digest: sha256:457539dbd781594eccd4ddf26a7aefdf08a2fff9dbeb1f601a22d9e7e3761fbc
Status: Downloaded newer image for feelpp/feelpp-env:latest
Hello World! 
----

We have called the `docker run` command which takes care of executing containers. We passed the argument `feelpp/feelpp-env` which is a Feel{plus}{plus} Ubuntu 16.10 container with the required programming and execution environment for Feel{plus}{plus}.
The first line tells us that there is no local copy of this Feel++ image. Docker checks automatically online on the link:http:://hub.docker.com[Docker Hub] if an image is available.

[NOTE]
======
`feelpp/` in `feelpp/feelpp-env` provides the organization name(or namespace) of the image and `feelpp-env` is the image name. Note also that Docker specifies a more complete name `feelpp/feelpp-env:latest` including the tag name `:latest`. We will see later how we defined the `latest` tag at the Feel++ organization. See <<FCS>> for more details.
======

Once the image is downloaded, Docker launches the container and executes the command we provided `echo "Hello World!"` from inside the container. The result of the command is showed on the last line of the output log above.

If you run the command again, you won't see the download part and the command will be executed very fast.

We can ask Docker to give us a shell using the following command
[source,bash]
----
$ docker run -it feelpp/feelpp-env
----
It provides a shell prompt from inside the container which is very similar to what you obtain when login with `ssh` on a remote machine. The flags `-i` and `-t` tell Docker to provide an interactive session (`-i`) with a TTY attached (`-t`).

[[FCS]]
== Feel++ Container System

The _Feel++ Container System_ (FCS) is organized in layers and provide a set of images.

=== Naming

The naming convention of the FCS allows the user to know where they come from and where they are stored on the link:http://hub.docker.com[Docker Hub]. The name of the images is built as follows

[source,bash]
----
feelpp/feelp-<component>[:tag]
----

where 

 * `feelpp/` is the namespace of the image and organization name 
 * `feelpp-<component>` the image name and Feel++ component
 * `[:tag]` an optional tag for the image, by default set to `:latest`
 
Feel++ images(components) are defined as layers in the FCS in the table below

.Table of the current components of the FCS
|===
| Component | Description | Built From

| `feelpp-env` | Execution and Programming environment | <OS> 
| `feelpp-libs`  | Feel++ libraries and tools | `feelpp-env`
| `feelpp-base` | Feel++ base applications | `feelpp-libs` 
| `feelpp-apps` | Feel++ toolbox applications  | `feelpp-base`

|===

| **Note:** `feelpp-env` depends on an operating system image `<OS>`, the recommended and default `<OS>` is Ubuntu 16.10. In the future, we will build upon the next Ubuntu LTS or Debian Stable releases. 

=== Tags

By default, the `:latest` tag is assumed in the name of the images, for example when running
[source,bash]
----
$ docker run -it feelpp/feelpp-apps
----
it is in fact `feelpp/feelpp-apps:latest` which is being launched.
The following table displays the 

|===
| Image |  Built from

| `feelpp-env:latest` | built from Ubuntu 16.10
| `feelpp-libs:latest` | built from `feelpp-env:latest`
| `feelpp-base:latest` | built from `feelpp-libs:latest`
| `feelpp-apps:latest` | built from `feelpp-base:latest`

|===

=== Host OS

As we said before the default Host OS is Ubuntu 16.10. 
However Docker shines in continuous integration. It provides a large set of operating system to build upon and allows to check the software in various context. The FCS takes advantage of Docker to build  `feelpp-libs` for several operating systems provided by `feelpp-env` and with different compilers any time a commit in the Feel++ repository is done.

|===
| Operating system | version | `feelpp-env` Tags | Compilers

| Ubuntu | 16.10 | `ubuntu-16.10`,  `latest` | GCC 6.x, Clang 3.9
| Ubuntu | 16.04 | `ubuntu-16.04` | GCC 6.x, Clang 3.8
| Debian | sid   | `debian-sid` | GCC 6.x, Clang 3.9,4.0
| Debian | testing | `debian-testing`| GCC 6.x, Clang 3.9

|===

If you are interested in testing Feel++ in these systems, you can run these flavors.

=== feelpp-env

=== feelpp-libs

=== feelpp-base

=== feelpp-apps

== Other Software

Feel++ deployed with Docker benefits 

:toc:
:toc-placement: macro
:toclevels: 3

toc::[]

== Introduction
Docker is a platform that allows to package applications and their dependencies with controlled versions, so that they work in any environment. This allows to have applications with consistent behaviours independently on the base operating system you are using, be it any Linux flavour, Windows or Mac OS X. For more information, please refer to the [main site](https://www.docker.com) or to [what is docker ?](https://www.docker.com/what-docker).

To install docker, please refer to docker [documentation](https://docs.docker.com).

== Building Feel++ inside a container

To use Feel++ with docker, you can rely on pre-built images or generate them yourself by writing a file name Dockerfile and that acts like a Makefile for docker.

== Prebuilt images on Docker Hub {#dockerhub}

Prebuilt images are available on the [Feel++ repository on Dockerhub](https://hub.docker.com/u/feelpp/).

Several images are available:
   
* `feelpp/dev-env` provides a working software environment for the latest version of Feel++ based on Ubuntu (currently Ubuntu 16.10),   
* `feelpp/develop` provides the working software environment, plus the feelpp library installed in the system. 
* +feelpp/apps+ provides the Feel++ applications

To get one of these images, you can use the `docker pull` command.   
Refer to the `Using the container` section of this page for the usage.

=== Runing Feel++ Applications

To run link:/Applications/readme.adoc[Feel++ main applications], you need first to create a directory where you will store the Feel++ simulation files. For example, type
[source,shell]
----
mkdir $HOME/feel
----
and then type the following docker command

[source,shell]
----
docker run -it -v $HOME/feel:/feel feelpp/apps:latest
----

The previous command will execute the latest `feelpp/apps` docker image in interactive mode in a terminal (`-ti`) and mount `$HOME/feel` in the directory `/feel` of the docker image.

> **Note** Note that mouting a host sub-directory on `/feel` is mandatory. If you don't, the Feel++ applications will exit due to lack of permissions.




