Evaluating function 
==================
:toc:
:toc-placement: macro

toc::[]

Once you have created an element, you may want to give it a value, that can depends on a lot of parameters ( mainly spaces, but others may apply ).

To do so, Feel++ relies on expressions.
We may use various kind of expressions :

== Built-in 

Let's begin with the evaluation of the expression $$ sin(\pi x)$$ on a unit circle.

First at all, we define the unit circle and its link:07-SpaceElements.adoc[function space] :

[import:"meshspace",unindent:"true"](../codes/05-myexporter.cpp)

Then the expression we would like to evaluate :

[import:"expr",unindent:"true"](../codes/05-myexporter.cpp)

`Px()` refers to the variable $$x$$ of our space.

With this,we can `project` it on our function space :

[import:"project",unindent:"true"](../codes/05-myexporter.cpp)

The expression will be evaluated on each point of our mesh.

In order to visualize the result, we create an exporter, named `exhi`, and add to it the projection. 

[import:"exporter",unindent:"true"](../codes/05-myexporter.cpp)

=== Code

[import:"all"](../codes/05-myexporter.cpp)

The list of the Feel++ Keyword is link:../QuickReference/keywords.adoc[here].

== Hard Coded 

In this second method, we will use Functor :

[import:"functor",unindent:"true"](../codes/myfunctor.cpp)

We create a unit square meshed by triangles and we define the associated function space : 

[import:"meshspace",unindent:"true"](../codes/myfunctor.cpp)

From this space, we can define two elements, here one equals to the variable $$x$$ and the other to the variable $$y$$, obtain from Functor class.

[import:"elements",unindent:"true"](../codes/myfunctor.cpp)

The data exportation is the final step to visualize our expression $$x$$ and $$y$$ on the defined mesh.

[import:"exporter",unindent:"true"](../codes/myfunctor.cpp)

=== Code 

[import:"all"](../codes/myfunctor.cpp)

The list of the Feel++ Keyword is link:../QuickReference/keywords.adoc[here].
