We want to solve a coupled electro-thermal problem on $$\Omega$$ with $$\partial\Omega=\Gamma=\Gamma_{C}\cup\Gamma_{T}=\Gamma_E\cup\Gamma_{in}\cup\Gamma_{out}$$. 

== Electrostatic problem
We need to find the electric potential $$V$$ by solving:
$$
\begin{align}
\nabla\cdot(-\sigma\nabla V) &= 0 &\text{ in } \Omega
\end{align}
$$where $$\sigma$$ is the electric conductivity. We denote by $$\mathbf{j} = - \sigma \nabla V$$ the electric current. On the boundary, we impose the electric potential on $$\Gamma_{in}$$ and $$\Gamma_{out}$$:

- $$V=0$$ on $$\Gamma_{in}$$
- $$V=V_{out}$$ on $$\Gamma_{out}$$.

We also want the other boundaries to be electrically insulating:

- $$-\sigma\nabla V\cdot\mathbf{n}=\mathbf{j}\cdot\mathbf{n} = 0$$ on $$\Gamma_E$$

And find the temperature $$T$$ by solving a thermal problem, where the source term comes from Joule effect:
$$
\begin{align}
\nabla\cdot(-k\nabla T) &= \sigma\nabla V\cdot \nabla V &\text{ in } \Omega
\end{align}
$$where $$k$$ is the thermal conductivity. +
The thermal exchanges with air are not considered, leading to a Neumann condition on $$\Gamma_T$$. While the thermal exchanges with the cooling water depends on a heat transfer coefficient $$h$$ and the water temperature $$T_w$$, leading to a Robin condition on $$\Gamma_C$$:

- $$-k\nabla T\cdot \mathbf{n} = 0$$ on $$\Gamma_T$$
- $$-k\nabla T\cdot\mathbf{n} = h(T-T_w)$$ on $$\Gamma_{C}$$

.Table of parameters for the simulation
|===
| Parameters | Ranges |  Nominal value | Units
| $$\sigma$$ | $$[52.10^{6};58.10^{6}]$$ | $$53\cdot 10^{6}$$ | $$S \cdot m^{-1}$$
| $$k$$ | $$[360;380]$$| $$370$$ | $$W\cdot m^{-1} \cdot K^{-1}$$
| $$T_w$$ | $$[280;310]$$ | 300 | K
| $$h$$ | $$[40000;50000]$$ | |
|===

