= Fluid Mechanics Models
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

{% include "git+https://github.com/feelpp/feelpp-benchmarking-book.git/CFD/readme.adoc#_Incompressible_Navier-Stokes_model" %}

== Properties


.Table of Models for `model` option
|===
| Model | Name 

| Navier-Stokes|`Navier-Stokes`

|===



== Materials

[source,json]
.Materials section
----
"Materials":
{
    "marker":
    {
        "name":"fluid",
        "rho":"1.0e3",
        "mu":"1.0"
    }
}
----

where `rho` the density in $$kg\cdot m^{-3}$$ and `mu` the dynamic viscosity in $$kg\cdot (m \cdot s)^{-1}$$ .

== Boundary Conditions

Boundary conditions and volumic forces are set in the json files
[source,json]
.Example for boundary conditions
----
"BoundaryConditions":
{
    "field":
    {
        "<condition type>":
        {
            "marker":
            {
                "expr": "value"
            }
        }
    }
}
----
where all component of vectorial field can be access with `<field>_x` for the $$x$$ component where `<field>` is the name of the vectorial field. +
The condition types are explain in the two following tables.

.Boundary conditions
|===
| Name | Options | Type 

| Dirichlet 
| faces, edges and component-wise
| "Dirichlet"

| Neumann 
| scalar, vectorial
| "Neumann_scalar" or "Neumann_vectorial"

|===


== Post Process

[source,json]
----
"PostProcess":
{
    "Fields":["field1","field2",...],
    "Measures":
    {
        "<measure type>":
        {
            "label":
            {
                "<range type>":"value",
                "fields":["field1","field3"]
            }
        }
    }
}
----

The fields allowed to be exported in the `Fields` section are:

- displacement
- velocity
- acceleration
- stress or normal-stress
- pressure
- material-properties
- pid
- fsi
- Von-Mises
- Tresca
- principal-stresses
- all

.Measure type and range type associated
|===
|Measure type | Range type | example

|Points | coords | "{0,0,0}"
|Maximum | markers | "marker1"
|Minimum | markers | "marker1"
|volume_variation* | - | "volume_variation":""
|===

*volume_variation does not take a set of point or of range, it is a volumic measure.

The fields on which one can do measures:

- volume_variation
- displacement
- velocity
- acceleration
- pressure
- principal-stress-0
- principal-stress-1
- principal-stress-2
- sigma_xx, sigma_xy, ...
