= Fluid Mechanics Models
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

== Models 

== Incompressible Navier-Stokes model

Navier-Stokes model is used to modelise incompressible Newtonian fluid. It can be describe by these conservative laws :

* momentum conservation equation 

$$
\rho_{f} \left. \frac{\partial\mathbf{u}_f}{\partial t} \right|_\mathrm{x}
+ \rho_{f} \left( \boldsymbol{u}_{f} \cdot \nabla_{\mathrm{x}} \right) \boldsymbol{u}_{f}
- \nabla_{\mathrm{x}} \cdot \boldsymbol{\sigma}_{f} = \boldsymbol{f}^t_f , \quad \text{ in } \Omega^t_f \times \left[t_i,t_f \right]
$$

* mass conservation equation

$$
\nabla_{\mathrm{x}} \cdot \boldsymbol{u}_{f} = 0                     , \quad \text{ in } \Omega^t_f \times \left[t_i,t_f \right] 
$$

We add to them the material constitutive equation :

$$
\boldsymbol{\sigma}_{f} = -p_f \boldsymbol{I} + \mu_f (\nabla_\mathrm{x} \boldsymbol{u}_f + (\nabla_\mathrm{x} \boldsymbol{u}_f)^T)
$$


|===
| Notation | Quantity | Unit 
|$$\rho_f$$|fluid density|$$kg/m^3$$
|$$\boldsymbol{u}_f$$|fluid velocity|$$m/s$$
|$$\boldsymbol{\sigma}_f$$|fluid stress tensor|$$N/m^2$$
|$$\boldsymbol{f}^t_f$$| source term | $$kg/(m ^3 \times s)$$
|$$p_f$$|pressure fields|$$kg/(m \times s^2)$$
|$$\mu_f$$| dynamic viscosity|$$kg/(m \times s)$$
|$$\bar{U}$$|characteristic inflow velocity|$$m/s$$
|$$\nu$$|kinematic viscosity|$$m^2/s$$
|$$L$$| characteristic length|$$m$$
|===

== JSON file

The JSON file contains the description of the fluid model. The next sub-sections describe the different entries in the file.

We start by given a name to our model

[source,json]
-----
"Name":"Fluid flow around a cylinder",
"ShortName":"flowcyl"
-----

=== Supported Fluid Model

We start with the fluid model itself.

.Table of Models for `model` option
|===
| Model | Name 
| Navier-Stokes|`Navier-Stokes`
| Stokes|`Stokes`
|===


=== Materials


Here is the list of symbols 
.Correspondance between fluid parameters and symbols in JSon files
|===
| Parameter | Symbol 
| $$\mu_f$$ | `mu`
| $$\rho_f$$  | `rho`
|===



[source,json]
.Materials section
----
"Materials":
{
    "marker":
    {
        "name":"fluid",
        "rho":"1.0e3",
        "mu":"1.0"
    }
}
----

where `rho` the density in $$kg\cdot m^{-3}$$ and `mu` the dynamic viscosity in $$kg\cdot (m \cdot s)^{-1}$$ .

=== Boundary Conditions

Boundary conditions and volumic forces are set in the json files
[source,json]
.Example for boundary conditions
----
"BoundaryConditions":
{
    "field":
    {
        "<condition type>":
        {
            "marker":
            {
                "expr": "value"
            }
        }
    }
}
----
where all component of vectorial field can be access with `<field>_x` for the $$x$$ component where `<field>` is the name of the vectorial field. +
The condition types are explain in the two following tables.

.Boundary conditions
|===
| Name | Options | Type 

| Dirichlet 
| faces, edges and component-wise
| "Dirichlet"

| Neumann 
| scalar, vectorial
| "Neumann_scalar" or "Neumann_vectorial"

|===


=== Post Process

[source,json]
----
"PostProcess":
{
    "Fields":["field1","field2",...],
    "Measures":
    {
        "<measure type>":
        {
            "label":
            {
                "<range type>":"value",
                "fields":["field1","field3"]
            }
        }
    }
}
----

The fields allowed to be exported in the `Fields` section are:

- displacement
- velocity
- acceleration
- stress or normal-stress
- pressure
- material-properties
- pid
- fsi
- Von-Mises
- Tresca
- principal-stresses
- all

.Measure type and range type associated
|===
|Measure type | Range type | example

|Points | coords | "{0,0,0}"
|Maximum | markers | "marker1"
|Minimum | markers | "marker1"
|volume_variation* | - | "volume_variation":""
|===

*volume_variation does not take a set of point or of range, it is a volumic measure.

The fields on which one can do measures:

- volume_variation
- displacement
- velocity
- acceleration
- pressure
- principal-stress-0
- principal-stress-1
- principal-stress-2
- sigma_xx, sigma_xy, ...

== Action

Let's finish with a simple example in order to show how this works and how to use them. We will interest us to a fluid flow into a cavity in 3D.

=== Feel++ code
Here is the code 

First at all, we define our model type with 

----
typedef FeelModels::FluidMechanics< Simplex<FEELPP_DIM,1>,
                                    Lagrange<OrderVelocity,Vectorial,Continuous,PointSetFekete>,
                                    Lagrange<OrderPressure,Scalar,Continuous,PointSetFekete> > model_type;
----

We choose here a $$\mathbb{P}_2$$ space for the velocity order and $$\mathbb{P}_1$$ space for the pressure order. This definition allows us to create our fluid model object FM like this
 
----
auto FM = model_type::New("fluid");
----

The method `New` retrieve all data from the configuration and json files, as well build a mesh if need.

With this object, we can initialize our model parameters, such as velocity or boundaries conditions. Data on our model and on the numeric solver are then save and print on the terminal. This is made by 

----
FM->init();
FM->printAndSaveInfo();
----

Now that our model is completed, we can solve the associated problem. To begin the resolution

----
FM->isStationary()
----

determine if our model is stationary or not.

If it is, then we need to solve our system only one time and export the obtained results.

----
FM->solve();
FM->exportResults();
----

If it's not, our model is time reliant, and a loop on time is necessary. Our model is then solve and the results are export at each time step.

----
 for ( ; !FM->timeStepBase()->isFinished(); FM->updateTimeStep() )
        {
            FM->solve();
            FM->exportResults();
        }
----

==== Code

[source,cpp]
----
{% include "../Examples/fluid_model.cpp" %}
----


=== Configuration file

The config file is used to define options,  linked to our case, we would have the possibility to change at will. It can be, for example, files paths as follows

----
[fluid]
geofile=$cfgdir/cavity3d.geo
filename=$cfgdir/cavity3d.json

[exporter]
directory=applications/models/fluid/cavity3d/$fluid_tag
----

It can also be resolution dependent parameters such as mesh elements size, methods used  to define our problem and solvers.

----
[fluid]
solver=Oseen #Picard,Newton

linearsystem-cst-update=false
jacobian-linear-update=false

snes-monitor=true
snes-maxit=100
snes-maxit-reuse=100
snes-ksp-maxit=1000
snes-ksp-maxit-reuse=100

pc-type=lu #gasm,lu,fieldsplit,ilu
----
In this case, we use Oseen to define our problem, we set the update of linear system constant and jacobian linear as "no update", we discretize values associated to SNES ( Scalable Nonlinear Equations Solvers ), and finally we choose LU as the preconditioner method.

==== Code

[source,cfg]
----
{% include "../Examples/cavity3d.cfg" %}
----

=== Json file

First at all, we define some general information like the name ( and short name ) and the model we would like to use

[source,json]
----
"Name": "Fluid Mechanics",
"ShortName":"Fluid",
"Model":"Navier-Stokes",
----

Then we define the link:#Material[material properties]. In our case, the fluid, define  by rho` its density in $$kg\cdot m^{-3}$$ and `mu` its dynamic viscosity in $$kg\cdot (m \cdot s)^{-1}$$, is the only material we have to define.

[source,json]
----
"Materials":
    {
        "Fluid":{
            "name":"myFluidMat",
            "rho":"1.0",
            "mu":"0.01"
        }
    },
----

The link:#Boundary_Conditions[boundary conditions] are the next aspect we define. Here, we impose on the velocity $$u_f$$ Dirichlet conditions at two specific places : `lid` and `wall`.

[source,json]
----
"BoundaryConditions":
    {
        "velocity":
        {
            "Dirichlet":
            {
                "lid":
                {
                    "expr":"{ 1,0,0}:x:y:z"
                },
                "wall":
                {
                    "expr":"{0,0,0}"
                }
            }
        }
    }
----

The link:#Post_Process[post process] aspect is the last one to define. We choose the fields we want to export ( velocity, pressure and pid ). Furthermore, we want to measure forces on `wall` and the pressure at point $$A$$.

[source,json]
----
"PostProcess":
    {
        "Fields":["velocity","pressure","pid"],
        "Measures":
        {
            "Forces":"wall",
            "Points":
            {
                "pointA":
                {
                    "coord":"{0.5,0.5,0.5}",
                    "fields":"pressure"
                }
            }
        }
    }
}
----

==== Code

[source,json]
----
{% include "../Examples/cavity3d.json" %}
----

=== Compilation/Execution

Once you've a build dir, you just have to realise the command `make` at 

--------------------
{buildir}/applications/models/fluid
--------------------

This will generate executables named `feelpp_application_fluid_*`. To execute it, you need to give the path of the cfg file associated to your case, with `--config-file`.

For example

----
./feelpp_application_fluid_3d --config-file={sourcedir}/applications/models/fluid/cavity/cavity3d.cfg
----

is how to execute the case ahead.

The result files are then stored by default in 

----
 feel/applications/models/fluid/{case_name}/
   {velocity_space}{pression_space}{Geometric_order}/{processor_used}
----

If we return once again at our example, the result files are in 

----
 feel/applications/models/fluid/cavity3d/P2P1G1/np_1
----


