= Fluid Mechanics Models
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

== Models 

{% include "NavierStokes.adoc" %}


= JSON file
== Properties


.Table of Models for `model` option
|===
| Model | Name 

| Navier-Stokes|`Navier-Stokes`

|===


== Materials

[source,json]
.Materials section
----
"Materials":
{
    "marker":
    {
        "name":"fluid",
        "rho":"1.0e3",
        "mu":"1.0"
    }
}
----

where `rho` the density in $$kg\cdot m^{-3}$$ and `mu` the dynamic viscosity in $$kg\cdot (m \cdot s)^{-1}$$ .

== Boundary Conditions

Boundary conditions and volumic forces are set in the json files
[source,json]
.Example for boundary conditions
----
"BoundaryConditions":
{
    "field":
    {
        "<condition type>":
        {
            "marker":
            {
                "expr": "value"
            }
        }
    }
}
----
where all component of vectorial field can be access with `<field>_x` for the $$x$$ component where `<field>` is the name of the vectorial field. +
The condition types are explain in the two following tables.

.Boundary conditions
|===
| Name | Options | Type 

| Dirichlet 
| faces, edges and component-wise
| "Dirichlet"

| Neumann 
| scalar, vectorial
| "Neumann_scalar" or "Neumann_vectorial"

|===


== Post Process

[source,json]
----
"PostProcess":
{
    "Fields":["field1","field2",...],
    "Measures":
    {
        "<measure type>":
        {
            "label":
            {
                "<range type>":"value",
                "fields":["field1","field3"]
            }
        }
    }
}
----

The fields allowed to be exported in the `Fields` section are:

- displacement
- velocity
- acceleration
- stress or normal-stress
- pressure
- material-properties
- pid
- fsi
- Von-Mises
- Tresca
- principal-stresses
- all

.Measure type and range type associated
|===
|Measure type | Range type | example

|Points | coords | "{0,0,0}"
|Maximum | markers | "marker1"
|Minimum | markers | "marker1"
|volume_variation* | - | "volume_variation":""
|===

*volume_variation does not take a set of point or of range, it is a volumic measure.

The fields on which one can do measures:

- volume_variation
- displacement
- velocity
- acceleration
- pressure
- principal-stress-0
- principal-stress-1
- principal-stress-2
- sigma_xx, sigma_xy, ...

== Action

Let's finish with a simple example in order to show how this works and how to use them. We will interest us to a fluid flow into a cavity in 3D.

=== Feel++ code
Here is the code 

[source,cpp]
----
{% include "../Examples/fluid_model.cpp" %}
----

First at all, we define our model type with 

----
typedef FeelModels::FluidMechanics< Simplex<FEELPP_DIM,1>,
                                    Lagrange<OrderVelocity,Vectorial,Continuous,PointSetFekete>,
                                    Lagrange<OrderPressure,Scalar,Continuous,PointSetFekete> > model_type;
----

We choose here a $$\mathbb{P}_2$$ space for the velocity order and $$\mathbb{P}_1$$ space for the pressure velocity. This definition allows us to create our fluid model object FM like this
 
----
auto FM = model_type::New("fluid");
----

With this object, we can initialize our model, with data from the config file, and by extension, the Json file. The useful data, such as , are then save and print on the terminal. This is made by 

----
FM->init();
FM->printAndSaveInfo();
----

Now that our model is completed, we can solve the associated problem. To begin the resolution

----
FM->isStationary()
----

determine if our model is stationary or not.

If it is, then we need to solve our system only one time and export the obtained results.

----
FM->solve();
FM->exportResults();
----

If it's not, our model is time reliant, and a loop on time is necessary. Our model is then solve and the results are export at each time step.

----
 for ( ; !FM->timeStepBase()->isFinished(); FM->updateTimeStep() )
        {
            FM->solve();
            FM->exportResults();
        }
----

=== Config and Json files
Then the configuration and the associated Json files

==== Config 
[source,cfg]
----
{% include "../Examples/cavity3d.cfg" %}
----

==== Json
[source,json]
----
{% include "../Examples/cavity3d.json" %}
----

First at all, we define some general information like the name ( and short name ) and the model we would like to use

[source,json]
----
"Name": "Fluid Mechanics",
"ShortName":"Fluid",
"Model":"Navier-Stokes",
----

Then we define the link:#Material[material properties]. In our case, the fluid is the only material we have to define by rho` its density in $$kg\cdot m^{-3}$$ and `mu` its dynamic viscosity in $$kg\cdot (m \cdot s)^{-1}$$ .

[source,json]
----
"Materials":
    {
        "Fluid":{
            "name":"myFluidMat",
            "rho":"1.0",
            "mu":"0.01"
        }
    },
----

The link:#Boundary\_Conditions[boundary conditions] are the next aspect we define. Here, we impose on the velocity $$u_f$$ Dirichlet conditions at two specific places : `lid` and `wall`.

[source,json]
----
"BoundaryConditions":
    {
        "velocity":
        {
            "Dirichlet":
            {
                "lid":
                {
                    "expr":"{ 1,0,0}:x:y:z"
                },
                "wall":
                {
                    "expr":"{0,0,0}"
                }
            }
        }
    }
----

The link:#Post\_Process[post process] aspect is the last one to define. We choose the fields we want to export ( velocity, pressure and pid ). Furthermore, we want to measure forces on `wall` and the pressure at point $$A$$.

[source,json]
----
"PostProcess":
    {
        "Fields":["velocity","pressure","pid"],
        "Measures":
        {
            "Forces":"wall",
            "Points":
            {
                "pointA":
                {
                    "coord":"{0.5,0.5,0.5}",
                    "fields":"pressure"
                }
            }
        }
    }
}
----