The Laplacian
=============
:toc:
:toc-placement: macro
:toclevels: 3

toc::[]

== Problem statement

We are interested in this section in the _conforming finite element approximation_ of the following problem:


Look for $$u$$ such that                              

$$     
\left\{\begin{split}                                                                                                                                                                                                                                                                           
     -\Delta u &= f \text{ in } \Omega\\                                                                                                                                       
      u &= g \text{ on } \partial \Omega_D\\
\frac{\partial u}{\partial n} &=h \text{ on } \partial \Omega_N\\
\frac{\partial u}{\partial n} + u &=l \text{ on } \partial \Omega_R
 \end{split}\right.
$$ 

CAUTION: $$\partial \Omega_D$$, $$\partial \Omega_N$$ and $$\partial \Omega_R$$ can be empty sets. In the case $$\partial \Omega_D =\partial \Omega_R = \emptyset$$, then the solution is known up to a constant.

[NOTE]
======
In the implementation presented later, $$\partial \Omega_D =\partial \Omega_N = \partial \Omega_R = \emptyset$$, then we set Dirichlet boundary conditions all over the boundary. The problem then reads like a standard laplacian with inhomogeneous Dirichlet boundary conditions:

Look for $$u$$ such that                              

$$                                                                                                                                                                                                                                                                            
-\Delta u = f\ \text{ in } \Omega,\quad u = g \text{ on } \partial \Omega
$$ 
======


== Variational formulation

We assume that $$f, h, l \in L^2(\Omega)$$. The weak formulation of the problem then reads:                                                                                                                                            
                                                                                                                                                                
Look for $$u \in H^1_{g,\Gamma_D}(\Omega)$$ such that                                                                                                                                    

$$                                                                                                                                                           
\displaystyle\int_\Omega \nabla u \cdot \nabla v +\int_{\Gamma_R} u v = \displaystyle \int_\Omega f\ v+ \int_{\Gamma_N} g\ v + \int_{\Gamma_R} l\ v,\quad \forall v \in H^1_{0,\Gamma_D}(\Omega)                                                                              
$$ 

== Conforming Approximation
                                                                                                                                                            
We now turn to the finite element approximation using Lagrange finite element. We assume $$\Omega$$ to be a segment in 1D, a polygon in 2D or a polyhedron in 3D.   
We denote $$V_\delta  \subset H^1(\Omega)$$ an approximation space such that $$V_{g,\delta} \equiv P^k_{c,\delta}\cap H^1_{g,\Gamma_D}(\Omega) $$.

The weak formulation reads: 

Look for $$u_\delta \in V_\delta  $$ such that                                                                                                                                    

$$                                                                                                                                                           
\displaystyle\int_{\Omega_\delta} \nabla u_{\delta} \cdot \nabla v_\delta +\int_{\Gamma_{R,\delta}} u_\delta\ v_\delta = \displaystyle \int_{\Omega_\delta} f\ v_\delta+ \int_{\Gamma_{N,\delta}} g\ v_\delta + \int_{\Gamma_{R,\delta}} l\ v_\delta,\quad \forall v_\delta \in V_{0,\delta}                                                      
$$ 

NOTE: from now on, we omit $$\delta$$ to lighten the notations. Be careful that it appears both the geometrical and approximation level.

[[implementation]]
== Feel++ Implementation   

In Feel{plus}{plus},  $$V_{g,\delta}$$ is not built but rather                                                                                                                 
$$P^k_{c,\delta}$$. 

NOTE: The Dirichlet boundary conditions can be treated using different techniques and we use from now on the elimination technique.

We start with the mesh
[include:"mesh",lang="feelpp"](qs_laplacian.cpp)

NOTE: the keyword `auto` enables type inference, for more details see link:https://en.wikipedia.org/wiki/C%2B%2B11#Type_inference[Wikipedia C{plus}{plus}11 page]. 

[import:lang="feelpp"](qs_laplacian.cpp)



Next the discretization setting
[include:"discr",lang="feelpp"](qs_laplacian.cpp)

the variational formulation
[include:"vf",lang="feelpp"](qs_laplacian.cpp)

next we solve
[include:"solve",lang="feelpp"](qs_laplacian.cpp)

and finally we export the results
[include:"export",lang="feelpp"](qs_laplacian.cpp)

== Testcases

The <<implementation>> comes with testcases in 2D and 3D.

=== Feel{plus}{plus}




