The Laplacian
=============
:toc:
:toc-placement: macro
:toclevels: 3

toc::[]

== Problem statement

We are interested in this section in the _conforming finite element approximation_ of the following problem:


Look for $$u$$ such that                              

$$     
\left\{\begin{split}                                                                                                                                                                                                                                                                           
     -\Delta u &= f \text{ in } \Omega\\                                                                                                                                       
      u &= g \text{ on } \partial \Omega_D\\
\frac{\partial u}{\partial n} &=h \text{ on } \partial \Omega_N\\
\frac{\partial u}{\partial n} + u &=l \text{ on } \partial \Omega_R
 \end{split}\right.
$$ 

== Variational formulation

We assume that $$f, h, l \in L^2(\Omega)$$. The weak formulation of the problem then reads:                                                                                                                                            
                                                                                                                                                                
Look for $$u \in H^1_{g,\Gamma_D}(\Omega)$$ such that                                                                                                                                    

$$                                                                                                                                                           
\displaystyle\int_\Omega \nabla u \cdot \nabla v +\int_{\Gamma_R} u v = \displaystyle \int_\Omega f\ v+ \int_{\Gamma_N} g\ v + \int_{\Gamma_R} l\ v,\quad \forall v \in H^1_{0,\Gamma_D}(\Omega)                                                                              
$$ 

== Conforming Approximation
                                                                                                                                                            
We now turn to the finite element approximation using Lagrange finite element. We assume $$\Omega$$ to be a segment in 1D, a polygon in 2D or a polyhedron in 3D.   
We denote $$V_\delta  \subset H^1(\Omega)$$ an approximation space such that $$V_{g,\delta} \equiv P^k_{c,\delta}\cap H^1_{g,\Gamma_D}(\Omega) $$.

The weak formulation reads: 

Look for $$u_\delta \in V_\delta  $$ such that                                                                                                                                    

$$                                                                                                                                                           
\displaystyle\int_{\Omega_\delta} \nabla u_{\delta} \cdot \nabla v_\delta +\int_{{\Gamma_R}_\delta} u_\delta\ v_\delta = \displaystyle \int_{\Omega_\delta} f\ v_\delta+ \int_{{\Gamma_N}_\delta} g\ v_\delta + \int_{{\Gamma_R}_\delta} l\ v_\delta,\quad \forall v_\delta \in V_{0,\delta}                                                      
$$ 

NOTE: from now on, we omit $$\delta$$ to lighten the notations. Be careful that it appears both the geometrical and approximation level.

== Feel++ Implementation   

In Feel{plus}{plus},  $$V_{g,\delta}$$ is not built but rather                                                                                                                 
$$P^k_{c,\delta}$$. 

NOTE: The Dirichlet boundary conditions can be treated using different techniques and we use from now on the elimination technique.

We start with the mesh

NOTE: the keyword `auto` enables type inference, for more details see link:https://en.wikipedia.org/wiki/C%2B%2B11#Type_inference[Wikipedia C{plus}{plus}11 page]. 

