= CMake and Feel++ applications
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

Feel\++ offers a development environment for solving partial differential equations. It uses many tools to cover the different steps  pre-processing, processing and post-processing and large range of numerical methods and needs. To this end it is crucial to have a powerful build environment. Feel\++ uses CMake from Kitware and provides various macros to help setting up your own application or research project.

== CMake macros

=== Setting up Feel++ environment

=== Adding a new application

=== Adding a new testcase

For a give application or multiple applications you may define testcases. testcases are difrectory containing a set of files that may include geometry, mesh, cfg or json files.

To define a new testcase case, create a sub-directory where your application, say `myapp` like in the previous section, stands and copy the required files there.

```sh
cd <source directory of my application>
mkdir mytestcase
# copy files (.geo, .msh, .cfg...) to mytestcase
...
```
then edit the `CMakeLists.txt` in your application directory and add the following line:

```cmake
feelpp_add_testcase(mytestcase)
```



