Compiling Feel++ from sources
=============================
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

== Quick start

[source,bash]
----
# Get Feel++ sources, either via git of packages
# Go into the source directory
# Create a build directory and go into it

# Generate the makefile
# If you do not have administration rights, you must specify the installation
# path with -DCMAKE_INSTALL_PREFIX=..., when using CMake
cmake .. -DCMAKE_C_COMPILER=/usr/bin/clang-3.6 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-3.6

# Compile and install the library
# You need to use sudo, if you didn't specify the CMAKE_INSTALL_PREFIX option
make install-feelpp-lib

# Compile the library and an example
make -j 4 feelpp_qs_laplacian

# execute one example
./quickstart/feelpp_qs_laplacian
----

== General information

Feel{plus}{plus} uses http://www.cmake.org[`CMake`] as its build system. Check that CMake is using `clang-3.5` (or a higher version) (or `g++`, but it has a huge memory footprint) as C{plus}{plus} compiler. You can set the compiler with following option :
```
-DCMAKE_CXX_COMPILER=<path>/clang++-3.5
``` 
where the `path` depends on your OS. By default, it should be `/usr/bin` or `/opt/local/bin`, but you can also change it with the command `ccmake` and press `t` for advanced options). +

There are different build type that you can set with `-DCMAKE_BUILD_TYPE` (case insensitive) :

* None
* Debug
* Release
* MinSizeRel
* RelWithDebInfo

In order to compile and install Feel{plus}{plus} on Linux systems (other than Mac OS X, if you have Mac OS X, please go to link:mac.adoc[Mac]), you have to install several dependencies before. Those libraries and programs are necessary for the compilation and installation of the Feel++ libraries.

This is the list of all the libraries you must have installed on your computer, and the `*-dev` packages for some of them.


> *Warning* Feel{plus}{plus} use C{plus}{plus}14 compilers. There is a major compatibility issue between llvm/clang and GCC compilers since GCC5 released the ABI tag which makes it impossible to compile Feel{plus}{plus} using llvm/clang with GCC5 or GCC6 standard libraries. Please see the following table to understand the working C{plus}{plus} compiler / C{plus}{plus} standard library combinations.

.Table C{plus}{plus} compilers and standard libraries combinations
|===
| Compiler  | Standard Library 

| clang (3.5, 3.6, 3.7, 3.8) | libstdc{plus}{plus} 4.9 
| clang  |  libc{plus}{plus} (corresponding clang version)
| GCC 5 | libstdc{plus}{plus} 5
| GCC 6 | libstdc{plus}{plus} 6

|===



.Table required tools to compile Feel++
|===
| Name | Minimum Version | Maximum Version | Notes

| CMake | 2.8.7 | -- | 
| MPI   | -- | -- | openmpi or mpich
| Boost | 1.55 | 1.61 | 
| PETSc | 3.2 | 3.7 | 
| Gmsh  | 2.8.7 | 2.12 | 
|===

.Table optional external libraries

|===
| Library | Notes

| Superlu | superlu and superlu_dist
| Suitesparse | umfpack (colamd,amd)
| OpenTURNS |
|===

.Table Optional tools
|===
| Tool | Notes

| Google perftools|
| Paraview | for visualisation purposes
| Gmsh application | for meshing purposes
|===

Note that all these packages are available under Debian GNU/Linux and Ubuntu. Once you have installed those dependencies, you can go to link:#Compiling[Compiling].

== Compiling 

> **Warning** It is not allowed to build the library in the top source directory.

It is recommended  to have a directory (e.g. `FEEL`) in which you have
both the sources and build directories.

[source,sh]
----
ls FEEL
feelpp/ # Sources
feel.opt/ # Build directory
----

In this case, `feelpp` is the top directory where the source have been downloaded, using git or tarballs.

`CMake` is used as it:

[source,sh]
----
 cd FEEL/feel.opt
 cmake ../feelpp -DCMAKE_CXX_COMPILER=/usr/bin/clang++-3.6 -DCMAKE_C_COMPILER=/usr/bin/clang-3.6 -DCMAKE_BUILD_TYPE=RelWithDebInfo
----

You can customize the build type in any way.
Please have a look at:

[source,sh]
----
 FEEL/feelpp/CMakeLists.txt
----

// <ndlr>: Where is the list ?
// or at the `List of Cmake Options` section.

## Per-system specific configuration

If you need to set specific CMake variables to fit an exotic system (e.g. supercomputer), you can create a machine file fitting this system. + 
To do so, simply create a file named `feelpp.machines.<name>.cmake` in the `cmake/machines` directory, where `<name>` is the machine name returned by the execution of `uname -n`. The file will automatically be recognized and loaded, when you will be compiling Feel++ on this system.  

## Compilation

Once CMake has done its work, you are now able to compile the library with:

[source,bash]
----
  make
----

You can speed up the compilation process, if you have a multicore processor. To do so, you can specify the number of parallel jobs `make` will be allowed to spawn by using the `-j` flag:

[source,bash]
----
  make -j <nbjobs>
----

> **Note** From now on, all commands should be typed in
  build directory (e.g `feel.opt`) or its subdirectories.

## Unit tests

Feel++ comes with built-in unit tests to ensure that the library is working correctly. You can launch basic tests based on the quickstart application by typing:

[source,bash]
----
  make check
----

Or you can execute the whole testsuite, by typing the following
command: (This might take a while)

[source,bash]
----
  make check-full
----
